site_url: https://rhondanayaheartofsoul.com/
logo_url: https://rhondanayaheartofsoul.com/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: public/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: 'Site Name', name: 'sitename', widget: 'string', hint: 'This is used for the site title' }
          - { label: 'Site Description', name: 'sitedescription', widget: 'string', hint: 'This is used as descriptive text for links that link to this site' }
          - { label: 'Site Email', name: 'siteemail', widget: 'string', required: false }
          - { label: 'Site Phone', name: 'sitephone', widget: 'string', required: false }
          - { label: 'Address', name: 'address', widget: 'string', required: false }
          - { label: 'Hero Image', name: 'heroimage', widget: 'image', required: false }
          - { label: 'Hero Title', name: 'herotitle', widget: 'string', required: false }
          - { label: 'Hero Content', name: 'herocontent', widget: 'string', required: false }
  - name: 'pages'
    label: 'Pages'
    folder: 'content/pages'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  - name: 'menu'
    label: 'Menu Items'
    folder: 'content/menu'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - label: "Category"
        name: "category"
        widget: "select"
        options: [ "Entree", "Dessert", "Appetizer", "Side" ]
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Image', name: 'image', widget: 'image', allow_multiple: false, required: false }
      - { label: 'Short Description', name: 'shortDescription', widget: 'markdown', required: false }
      - { label: 'Description', name: 'description', widget: 'markdown', required: false }
      - { label: 'Price', name: 'price', widget: 'number', value_type: 'float', required: true }
      - { label: 'Featured', name: 'featured', widget: 'boolean', required: false }
      - { label: 'Active', name: 'active', widget: 'boolean', required: false }
